pinconfig:
  description: >
    This section shows how the RPi's pins are configured.
    'pin' is the GPIO/BCM number for the pin.
    'physical' is the physical pin number.
  cameras:
    camera-mux:
      pin: 17
      physical: 11
    front-camera:
      # The name as reported by gst-device-monitor-1.0 Video
      id: "TODO"
      mux-active-level: "LOW"
      enabled: False
    rear-camera:
      # The name as reported by gst-device-monitor-1.0 Video
      id: "/base/axi/pcie@120000/rp1/i2c@88000/imx219@10"
      mux-active-level: "HIGH"
      enabled: True
  mcu:
    swdio:
      pin: 5
      physical: 29
    swclk:
      pin: 6
      physical: 31
    spi0-ce:
      pin: 8
      physical: 24
    spi0-miso:
      pin: 9
      physical: 21
    spi0-mosi:
      pin: 10
      physical: 19
    spi0-sclk:
      pin: 11
      physical: 23
  screen:
    i2c-sda:
      pin: 2
      physical: 3
    i2c-scl:
      pin: 3
      physical: 5
    dsi:
      description: "The DSI identifier returned by wlr-randr"
      id: "DSI-2"
moduleconfig:
  description: >
    This section shows the various modules' specific customizations.
  gstreamer-utils:
    queue-params:
      description: >
        This section contains overrides for the default parameters of GStreamer queues.
        See https://gstreamer.freedesktop.org/documentation/coreelements/queue.html?gi-language=c#properties
      max-buffers: 3
      max-bytes: 0
      max-time: 0
      leaky: "no"
    dot-graph:
      save: True
      dpath: "./"
    hailo:
      description: >
        This section describes params for HAILO-specific GStreamer elements.
      post-process-folder-path: "/usr/lib/aarch64-linux-gnu/hailo/tappas/post_processes"
      cropping-algorithm-folder-path: "/usr/lib/aarch64-linux-gnu/hailo/tappas/post_processes/cropping_algorithms"
      cropping-algorithm: "whole-buffer"
      base-model-folder-path: "/usr/share/hailo-models"
    logging:
      # MEMDUMP, TRACE, LOG, DEBUG, INFO, FIXME, WARNING, ERROR, NONE ; See https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=python
      level: "ERROR"
  logging:
    log-file-path: "/logs/creaturepod.log"
    log-file-path-dev: "./creaturepod.log"
    # DEBUG, INFO, WARNING, ERROR
    log-level: "DEBUG"
    log-to-console: True
  screen:
    timeout-seconds: 5
