pinconfig:
  description: >
    This section shows how the RPi's pins are configured.
    'pin' is the GPIO/BCM number for the pin.
    'physical' is the physical pin number.
  cameras:
    camera-mux:
      pin: 17
      physical: 11
    front-camera:
      # The 'id' as reported by Picamera2.global_camera_info() ; need to figure out the camera mux
      id: "cam0"
      mux-active-level: "LOW"
    rear-camera:
      # The 'id' as reported by Picamera2.global_camera_info() ; need to figure out the camera mux
      id: "cam1"
      mux-active-level: "HIGH"
  mcu:
    swdio:
      pin: 5
      physical: 29
    swclk:
      pin: 6
      physical: 31
    spi0-ce:
      pin: 8
      physical: 24
    spi0-miso:
      pin: 9
      physical: 21
    spi0-mosi:
      pin: 10
      physical: 19
    spi0-sclk:
      pin: 11
      physical: 23
  screen:
    i2c-sda:
      pin: 2
      physical: 3
    i2c-scl:
      pin: 3
      physical: 5
moduleconfig:
  description: >
    This section shows the various modules' specific customizations.
  gstreamer-utils:
    queue-params:
      description: >
        This section contains overrides for the default parameters of GStreamer queues.
        See https://gstreamer.freedesktop.org/documentation/coreelements/queue.html?gi-language=c#properties
      max-buffers: 3
      max-bytes: 0
      max-time: 0
      leaky: "no"
  logging:
    log-file-path: "/logs/creaturepod.txt"
    log-file-path-dev: "./creaturepod.txt"
    # DEBUG, INFO, WARNING, ERROR
    log-level: "DEBUG"
  screen:
    timeout-seconds: 5
